name: automerge
on:
  status: {}
  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed
  check_run:
    types:
      - completed
  pull_request:
    types:
      - labeled
      - unlabeled
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
      - push
      - synchronize
jobs:
  automerge:
    name: Auto Merge
    runs-on: ubuntu-latest
    steps:
      - name: Merge pull requests
        uses: blake-newman/automerge-action@d498b78
        env:
          GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"
          UPDATE_LABEL: "ready-to-update"
          UPDATE_METHOD: "rebase"
          LABELS: "!wip, required"
