name: automerge
on:
  check_run:
    types:
      - completed
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  status: {}
jobs:
  automerge:
    name: Auto Merge
    runs-on: ubuntu-latest
    steps:
      - name: Merge pull requests
        uses: blake-newman/automerge-action@172c19064db23fbf9797c4d8ccea308f50de3bd5
        env:
          GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"
          LABELS: "!wip, required"
